import { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import toast from 'react-hot-toast';
import api, { getError } from '../../api/client';
import { ArrowLeft } from 'lucide-react';

export default function EmployeeDetailPage() {
  const { id } = useParams();
  const [emp, setEmp] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (id === 'new') {
      setLoading(false);
      return;
    }
    api
      .get(`/employees/${id}`)
      .then(({ data }) => setEmp(data))
      .catch((err) => toast.error(getError(err)))
      .finally(() => setLoading(false));
  }, [id]);

  if (loading) {
    return (
      <div className="flex h-64 items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-brand-200 border-t-brand-600" />
      </div>
    );
  }

  if (id === 'new') {
    return (
      <div className="space-y-4">
        <Link to="/employees" className="inline-flex items-center gap-1 text-sm text-brand-600">
          <ArrowLeft className="h-4 w-4" /> Back
        </Link>
        <div className="card">
          <h1 className="text-xl font-bold">Add Employee</h1>
          <p className="mt-2 text-sm text-slate-500">
            Employee creation form will be wired to <code>POST /api/employees</code>. EMPID is generated by the backend and is immutable.
          </p>
        </div>
      </div>
    );
  }

  if (!emp) {
    return <div className="card text-center text-slate-500">Employee not found</div>;
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link to="/employees" className="rounded-lg p-2 hover:bg-slate-100 dark:hover:bg-slate-800">
          <ArrowLeft className="h-5 w-5" />
        </Link>
        <div>
          <p className="font-mono text-xs text-brand-600">{emp.employeeCode}</p>
          <h1 className="text-2xl font-bold">
            {emp.firstName} {emp.middleName} {emp.lastName}
          </h1>
          <p className="text-sm text-slate-500">
            {emp.designation?.title} · {emp.department?.name}
          </p>
        </div>
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        <div className="card space-y-3">
          <h2 className="font-semibold">Personal</h2>
          <dl className="grid grid-cols-2 gap-2 text-sm">
            <dt className="text-slate-500">Email</dt>
            <dd>{emp.email}</dd>
            <dt className="text-slate-500">Phone</dt>
            <dd>{emp.phone || '—'}</dd>
            <dt className="text-slate-500">Gender</dt>
            <dd>{emp.gender || '—'}</dd>
            <dt className="text-slate-500">Status</dt>
            <dd>
              <span className="badge bg-green-100 text-green-800 dark:bg-green-950 dark:text-green-300">
                {emp.status}
              </span>
            </dd>
            <dt className="text-slate-500">Joining date</dt>
            <dd>{emp.joiningDate ? new Date(emp.joiningDate).toLocaleDateString() : '—'}</dd>
          </dl>
        </div>

        <div className="card space-y-3">
          <h2 className="font-semibold">Organization</h2>
          <dl className="grid grid-cols-2 gap-2 text-sm">
            <dt className="text-slate-500">Department</dt>
            <dd>{emp.department?.name || '—'}</dd>
            <dt className="text-slate-500">Designation</dt>
            <dd>{emp.designation?.title || '—'}</dd>
            <dt className="text-slate-500">Branch</dt>
            <dd>{emp.branch?.name || '—'}</dd>
          </dl>
        </div>

        {emp.salary && (
          <div className="card space-y-3 lg:col-span-2">
            <h2 className="font-semibold">Salary structure</h2>
            <dl className="grid grid-cols-2 gap-2 text-sm sm:grid-cols-4">
              <dt className="text-slate-500">Basic</dt>
              <dd className="font-medium">{Number(emp.salary.basicSalary).toLocaleString()}</dd>
              <dt className="text-slate-500">Housing</dt>
              <dd>{Number(emp.salary.housingAllowance || 0).toLocaleString()}</dd>
              <dt className="text-slate-500">Transport</dt>
              <dd>{Number(emp.salary.transportAllowance || 0).toLocaleString()}</dd>
              <dt className="text-slate-500">Other</dt>
              <dd>{Number(emp.salary.otherAllowance || 0).toLocaleString()}</dd>
            </dl>
          </div>
        )}
      </div>
    </div>
  );
}
